#----------DEV----------
spring.data.mongodb.application.name = ses
spring.data.mongodb.database = hddt-demo
spring.data.mongodb.host = 127.0.0.1
spring.data.mongodb.port = 27017
spring.data.mongodb.username = hddt-demo
spring.data.mongodb.password = IE3Za4vOPJvAHjzhxekA
spring.data.mongodb.repositories.enabled=true
